package dao;

import java.sql.Connection;
import java.sql.Date;
import java.text.DateFormat;
import java.text.Format;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;


import dao.SingletonConnection;

import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
public class Testdao {
	public static void main(String[] args) throws ParseException {
		// TODO Auto-generated method stub
		//Connection conn=SingletonConnection.getConnection();
		//System.out.println(new java.sql.Date(System.currentTimeMillis()));


		Connection cnx =DAOFACTORY.getConnection();


		String ss = "ayoub";
		System.out.println("Your HashCode Generated by MD5 is: " + getMd5(ss));

		// f6fdffe48c908deb0f4c3bd36c032e72



	}
	public static  String getMd5(String input){
		try {
			// Static getInstance method is called with hashing MD5
			MessageDigest md = MessageDigest.getInstance("MD5");
			//  of an input digest() return array of byte
			byte[] messageDigest = md.digest(input.getBytes());
			// Convert byte array into signum representation
			BigInteger no = new BigInteger(1, messageDigest);
			// Convert message digest into hex value
			String hashtext = no.toString(16);
			while (hashtext.length() < 32) {
				hashtext = "0" + hashtext;
			}
			return hashtext;
		} 
		catch (NoSuchAlgorithmException e) {
			throw new RuntimeException(e);
		}
	}

	

}
